---
services:
  proxy:
    # image: ghcr.io/dangnghia1997/go-gin-woocommerce-proxy:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - WP_API_URL=${WP_API_URL}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}
      - WP_APP_USERNAME=${WP_APP_USERNAME}
      - WP_APP_PASSWORD=${WP_APP_PASSWORD}
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
