---
services:
  proxy:
    #build: .
    image: ghcr.io/dangnghia1997/go-gin-woocommerce-proxy:1.0
    ports:
      - "8080:8080"
    environment:
      - WP_API_URL=${WP_API_URL}
      - WOOCOMMERCE_API_URL=${WOOCOMMERCE_API_URL}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
