name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Add your Docker build and push steps here
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/go-proxy-app:amd64 .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/go-proxy-app:amd64
